#!/usr/bin/env python3
"""spm_model.py

Run SPM model estimation from Python using spm-python when available.

Usage:
  python3 utils/spm_model.py model --batch /path/to/spm_batch.m --output /path/to/output_dir

This script will try to use `spm-python` to initialize SPM and run the
generated batch file. If `spm-python` cannot run the batch (or is not
installed), it exits with non-zero so the caller can fallback to the
standalone runner or MATLAB.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def run_via_spm_python(batch_m: str, utils_dir: str) -> int:
    """Attempt to run the MATLAB batch using spm-python.

    Returns 0 on success, non-zero on failure.
    """
    try:
        # set MATLABPATH so run() or the batch can find helper functions
        prev = os.environ.get('MATLABPATH', '')
        if prev:
            os.environ['MATLABPATH'] = utils_dir + os.pathsep + prev
        else:
            os.environ['MATLABPATH'] = utils_dir

        import spm  # type: ignore

        # initialize SPM using the package API
        try:
            spm.spm('defaults', 'FMRI')
        except Exception:
            pass
        try:
            spm.spm_jobman('initcfg')
        except Exception:
            pass

        # If a JSON representation of the matlabbatch exists alongside the
        # generated .m batch (generated by our generate_spm_batch.py), prefer
        # reconstructing the matlabbatch in Python and calling spm_jobman
        # directly. This avoids relying on MATLAB-run parsing of .m files.
        # Prefer an on-disk MATLAB .mat if present (written by generate_spm_batch.py)
        batch_mat = str(Path(batch_m).with_suffix('.mat'))
        if os.path.isfile(batch_mat):
            try:
                from scipy.io import loadmat
                loaded = loadmat(batch_mat, simplify_cells=True)
                # 'matlabbatch' may be present
                if 'matlabbatch' in loaded:
                    matlabbatch = loaded['matlabbatch']
                    try:
                        spm.spm_jobman('initcfg')
                    except Exception:
                        pass
                    try:
                        spm.spm_jobman('run', matlabbatch)
                    except Exception as e:
                        print(f'Error running matlabbatch from .mat via spm_jobman: {e}', file=sys.stderr)
                        return 6
                    return 0
            except Exception as e:
                print(f'Failed to load/execute batch .mat: {e}', file=sys.stderr)
                # fall through to JSON or .m paths

        batch_json = str(batch_m) + '.json'
        if os.path.isfile(batch_json):
            try:
                with open(batch_json, 'r') as bj:
                    meta = json.load(bj)

                # Construct a minimal matlabbatch structure expected by SPM
                # using Python nested dicts/lists. spm-python will convert
                # these into MATLAB structs/cells when calling into SPM.
                facts = meta.get('facts', [])
                icell = meta.get('icell', [])
                covs = meta.get('covariates', [])

                matlabbatch = [
                    {
                        'spm': {
                            'stats': {
                                'factorial_design': {
                                    'dir': [meta.get('dir')],
                                    'des': {
                                        'fd': {
                                            'fact': [
                                                {k: v for k, v in f.items()} for f in facts
                                            ],
                                            'icell': [
                                                {'scans': c.get('scans', [])} for c in icell
                                            ]
                                        }
                                    },
                                    'cov': [
                                        {'c': cov.get('c', []), 'cname': cov.get('cname', ''), 'iCFI': 1, 'iCC': 1}
                                        for cov in covs
                                    ],
                                    'masking': {'tm': 0, 'im': 1, 'em': ''},
                                }
                            }
                        }
                    }
                ]

                # initialize and run
                try:
                    spm.spm_jobman('initcfg')
                except Exception:
                    pass

                try:
                    spm.spm_jobman('run', matlabbatch)
                except Exception as e:
                    print(f'Error running matlabbatch via spm_jobman: {e}', file=sys.stderr)
                    return 5

                return 0
            except Exception as e:
                print(f'Failed to load/execute batch JSON: {e}', file=sys.stderr)
                # fall through to trying the .m runner below

        # Attempt to run the .m batch by calling MATLAB's run function
        # spm-python exposes MATLAB functions via the spm module; try to call
        # the MATLAB builtin 'run' by looking it up on the spm module.
        # Some spm-python versions may proxy MATLAB builtins; if so try
        # to call them through the module. Otherwise the JSON path above
        # should be preferred. Attempt to call spm.spm_jobman on the
        # assumption the .m file defines `matlabbatch` in the workspace.
        try:
            spm.spm_jobman('run', 'matlabbatch')
        except Exception:
            print('spm-python could not execute the .m batch via spm_jobman run fallback', file=sys.stderr)
            return 2

        return 0
    except Exception as e:
        print(f'spm-python execution failed: {e}', file=sys.stderr)
        return 4
    finally:
        # restore MATLABPATH
        if prev:
            os.environ['MATLABPATH'] = prev
        else:
            os.environ.pop('MATLABPATH', None)


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest='cmd')
    m = sub.add_parser('model')
    m.add_argument('--batch', required=True, help='Path to spm_batch.m')
    m.add_argument('--output', required=True, help='Output directory (SPM.mat will be written here)')
    args = p.parse_args(argv)

    if args.cmd != 'model':
        p.print_help()
        return 2

    batch_m = os.path.abspath(args.batch)
    output_dir = os.path.abspath(args.output)
    utils_dir = os.path.abspath(os.path.join(os.path.dirname(__file__)))

    if not os.path.isfile(batch_m):
        print(f'Batch file not found: {batch_m}', file=sys.stderr)
        return 10

    # Try spm-python
    rc = run_via_spm_python(batch_m, utils_dir)
    return rc


if __name__ == '__main__':
    sys.exit(main())
