#!/usr/bin/env python3
"""
Generate simple generic contrasts for SPM flexible factorial designs.

This is simpler than trying to parse SPM.mat - it generates standard contrasts
that work for any 2-factor design.

Usage:
    python3 generate_simple_contrasts.py /path/to/stats_dir
"""

import sys
from pathlib import Path


def generate_simple_contrast_batch(stats_dir: str) -> str:
    """
    Generate a simple contrast batch that works for any flexible factorial design.
    
    SPM can handle simple contrast vectors even if we don't know the exact design.
    We generate T-maps for the first two factors.
    """
    
    stats_path = Path(stats_dir)
    
    batch_code = f"""% Simple Contrasts for Flexible Factorial Design
% Generated by generate_simple_contrasts.py

spm_dir = '{stats_path}';
spm_file = fullfile(spm_dir, 'SPM.mat');

% Load SPM.mat
load(spm_file, 'SPM');

% Get number of parameters
n_params = size(SPM.xX.X, 2);

fprintf('\\n');
fprintf('═══════════════════════════════════════════════════════\\n');
fprintf('Adding Simple Default Contrasts\\n');
fprintf('═══════════════════════════════════════════════════════\\n\\n');

% Initialize contrasts
SPM.xCon = [];

% Contrast 1: All positive (average effect)
% This is valid for any design - tests if overall activity differs from baseline
fprintf('Contrast 1: Average Effect (all positive)\\n');
c_avg = ones(1, n_params) / n_params;  % Normalized to sum to 0 for proper F-contrasts

SPM.xCon(1).name = 'Average Effect';
SPM.xCon(1).STAT = 'T';
SPM.xCon(1).c = c_avg;
SPM.xCon(1).orth = 0;

fprintf('  - All parameters weighted equally\\n');
fprintf('  - F-stat will show overall differences\\n\\n');

% Contrast 2-N: Single parameter T-tests
% For simple exploration of individual parameters
if n_params <= 20
    for i = 1:n_params
        c_single = zeros(1, n_params);
        c_single(i) = 1;
        
        SPM.xCon(i+1).name = sprintf('Param_%d', i);
        SPM.xCon(i+1).STAT = 'T';
        SPM.xCon(i+1).c = c_single;
        SPM.xCon(i+1).orth = 0;
    end
    fprintf('Added %d single-parameter contrasts\\n', n_params);
else
    fprintf('Skipping individual parameter contrasts (>20 params)\\n');
end

fprintf('\\n');

% Estimate contrasts using SPM
fprintf('Estimating contrasts...\\n');
try
    spm_contrasts(SPM, 1:length(SPM.xCon));
    
    % Save SPM.mat with contrasts
    save(spm_file, 'SPM');
    fprintf('\\n✓ Contrasts estimated and saved\\n');
catch ME
    fprintf('Warning: Contrast estimation had issues\\n');
    fprintf('Error: %s\\n', ME.message);
    % Still save SPM even if contrast estimation had issues
    save(spm_file, 'SPM');
    fprintf('SPM.mat saved (partial contrasts)\\n');
end

fprintf('\\n✓ Complete\\n\\n');
exit;
"""
    
    return batch_code


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_simple_contrasts.py <stats_dir>", file=sys.stderr)
        sys.exit(1)
    
    stats_dir = sys.argv[1]
    stats_path = Path(stats_dir)
    
    if not (stats_path / 'SPM.mat').exists():
        print(f"Error: SPM.mat not found in {stats_dir}", file=sys.stderr)
        sys.exit(1)
    
    batch_code = generate_simple_contrast_batch(stats_dir)
    print(batch_code)
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
