#!/usr/bin/env python3
"""
Generate VBM-specific mask from a random smoothed subject image using nibabel.
This is a safer replacement for the MATLAB-based `generate_vbm_mask` which
occasionally caused segmentation faults in some MATLAB builds.

Usage:
    python3 generate_vbm_mask.py --cat12-dir /path/to/cat12 --smoothing 6 --output-dir /path/to/results --modality vbm

The script writes `mask_vbm.nii` into the output directory.
"""
import argparse
import glob
import os
import random
import sys
import numpy as np

try:
    import nibabel as nib
except Exception as e:
    print("Error: nibabel is required to run this script. Install with: pip install nibabel")
    raise


def find_smoothed_images(cat12_dir, smoothing):
    base = os.path.join(cat12_dir, 'data', 'cat12')
    pattern1 = os.path.join(base, '**', 'mri', f's{int(smoothing)}mwp1r*.nii')
    files = glob.glob(pattern1, recursive=True)
    if not files:
        pattern2 = os.path.join(base, '**', 'mri', f's{int(smoothing)}mwp1*.nii')
        files = glob.glob(pattern2, recursive=True)
    return sorted(files)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--cat12-dir', required=True)
    parser.add_argument('--smoothing', type=float, default=6)
    parser.add_argument('--output-dir', required=True)
    parser.add_argument('--modality', default='vbm')
    args = parser.parse_args()

    cat12_dir = args.cat12_dir
    smoothing = args.smoothing
    output_dir = args.output_dir
    modality = args.modality

    if modality != 'vbm':
        print('Only vbm modality supported by this script')
        sys.exit(1)

    # DEPRECATION / BEHAVIOR CHANGE:
    # The pipeline now prefers a canonical repo-level mask at
    # stats/templates/brainmask_GMtight.nii. If that template exists we
    # copy it into the output directory and exit — no per-results VBM mask
    # will be generated by default.
    repo_root = os.path.dirname(os.path.dirname(__file__))
    template_mask = os.path.join(repo_root, 'templates', 'brainmask_GMtight.nii')
    if os.path.isfile(template_mask):
        print('\nNOTICE: Detected repo template mask:')
        print(f'  {template_mask}')
        print('The pipeline prefers the canonical mask and will not generate a VBM-specific mask.')
        os.makedirs(output_dir, exist_ok=True)
        dest = os.path.join(output_dir, 'brainmask_GMtight.nii')
        try:
            import shutil
            shutil.copy2(template_mask, dest)
            print(f'Copied template mask to output dir: {dest}\n')
            return
        except Exception as e:
            print(f'Warning: failed to copy template mask: {e}. Falling back to generation.')


    print('\n' + '═' * 80)
    print('Generating VBM-Specific Mask')
    print('═' * 80 + '\n')

    print(f'Searching for smoothed {modality} images in:')
    print(cat12_dir + '\n')

    files = find_smoothed_images(cat12_dir, smoothing)
    if not files:
        print(f'No smoothed {modality} images found for smoothing={smoothing}mm in {cat12_dir}')
        sys.exit(1)

    print(f'✓ Found {len(files)} smoothed {modality} images\n')

    selected = random.choice(files)
    idx = files.index(selected) + 1
    print(f'Selected random image (index {idx} of {len(files)}):')
    print(selected + '\n')

    img = nib.load(selected)
    data = img.get_fdata(dtype=np.float32)
    # Use ASCII 'x' for dimension printing to avoid non-ASCII characters
    print(f'Image dimensions: {data.shape[0]} x {data.shape[1]} x {data.shape[2]}')
    print(f'Value range: [{np.nanmin(data):.4f}, {np.nanmax(data):.4f}]\n')

    mask = data > 0.1
    vox_in_mask = int(np.nansum(mask))
    total_vox = int(mask.size)
    perc = 100.0 * vox_in_mask / total_vox
    print(f'✓ Created mask with values > 0.1')
    print(f'Voxels in mask: {vox_in_mask} / {total_vox} ({perc:.2f}%)\n')

    os.makedirs(output_dir, exist_ok=True)
    mask_file = os.path.join(output_dir, 'mask_vbm.nii')

    mask_img = nib.Nifti1Image(mask.astype(np.uint8), img.affine, img.header)
    # Ensure datatype is uint8
    mask_img.header.set_data_dtype(np.uint8)

    nib.save(mask_img, mask_file)

    print(f'✓ Mask saved to:\n{mask_file}\n')
    print('Mask Statistics:')
    print(f'  Mask file: {mask_file}')
    print(f'  Voxels included: {vox_in_mask}')
    print(f'  Voxels excluded: {total_vox - vox_in_mask}')
    print('  Threshold: > 0.1\n')


if __name__ == '__main__':
    main()
