% SPM Batch: Flexible Factorial Design (Well-Conditioned)
% Auto-generated by generate_spm_batch.py
% Analysis: vbm (smoothing: 8mm)
%
% IMPORTANT: This design uses ONLY repeated measures factors (Group_by_Time)
% WITHOUT subject factors to avoid ill-conditioned design matrices.
% Subject dependencies are handled through the repeated measures structure.

matlabbatch{1}.spm.stats.factorial_design.dir = {'/tmp/test_output'};

%% Factor 1: Group (between-subject, independent)
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(1).name = 'Group';
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(1).levels = 3;
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(1).dept = 0;  % Independent (between-subject)
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(1).variance = 1;  % Unequal variance
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(1).gmsca = 0;  % No grand mean scaling
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(1).ancova = 0;  % Not ANCOVA

%% Factor 2: Time (within-subject, repeated measures)
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(2).name = 'Time';
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(2).levels = 3;
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(2).dept = 1;  % Dependent (within-subject, repeated measures)
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(2).variance = 1;  % Unequal variance (default assumption)
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(2).gmsca = 0;  % No grand mean scaling
matlabbatch{1}.spm.stats.factorial_design.des.fd.fact(2).ancova = 0;  % Not ANCOVA

%% Cells (Group_by_Time combinations)
%% Each cell contains scans from the same group at the same timepoint
%% SPM will automatically handle within-subject dependencies
% Cell 1: control_by_1
matlabbatch{1}.spm.stats.factorial_design.des.fd.icell(1).levels = [1 1];
matlabbatch{1}.spm.stats.factorial_design.des.fd.icell(1).scans = {
    '/Volumes/Thunder/129_PK01/cat12/data/cat12/sub-1291003/mri/s8mwp1rsub-1291003_ses-1_acq-mprage_T1w.nii,1'
};

% Cell 2: control_by_2
matlabbatch{1}.spm.stats.factorial_design.des.fd.icell(2).levels = [1 2];
matlabbatch{1}.spm.stats.factorial_design.des.fd.icell(2).scans = {
    '/Volumes/Thunder/129_PK01/cat12/data/cat12/sub-1291003/mri/s8mwp1rsub-1291003_ses-2_acq-mprage_T1w.nii,1'
};

% Cell 3: control_by_3
matlabbatch{1}.spm.stats.factorial_design.des.fd.icell(3).levels = [1 3];
matlabbatch{1}.spm.stats.factorial_design.des.fd.icell(3).scans = {
    '/Volumes/Thunder/129_PK01/cat12/data/cat12/sub-1291003/mri/s8mwp1rsub-1291003_ses-3_acq-mprage_T1w.nii,1'
};


%% Covariates
% No covariates

%% Main effects & interactions
matlabbatch{1}.spm.stats.factorial_design.des.fd.contrasts = 1;  % Create F-contrasts for main effects

%% Global calculation & masking
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;  % No threshold masking
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;  % Implicit mask (exclude voxels with zeros)
% Prefer the repo-level canonical mask (CAT12 tight) if available
matlabbatch{1}.spm.stats.factorial_design.masking.em = {'/Volumes/Thunder/129_PK01/cat12/stats/templates/brainmask_GMtight.nii'};  % canonical explicit mask
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;  % Omit global calculation
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;  % No grand mean scaling
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;  % Normalize globals
