#!/usr/bin/env python3
import os
import argparse
import subprocess
import sys
import configparser
from pathlib import Path

def get_config_defaults():
    """Read defaults from config/config.ini"""
    defaults = {
        'matlab_exe': '/Applications/MATLAB_R2025b.app/bin/matlab',
        'spm_path': ''
    }
    
    workspace_root = Path(__file__).resolve().parents[2]
    config_file = workspace_root / "config" / "config.ini"
    
    if config_file.exists():
        config = configparser.ConfigParser()
        try:
            config.read(config_file)
            if 'MATLAB' in config:
                if config['MATLAB'].get('exe'):
                    defaults['matlab_exe'] = config['MATLAB'].get('exe')
            if 'SPM' in config:
                if config['SPM'].get('path'):
                    defaults['spm_path'] = config['SPM'].get('path')
        except Exception as e:
            print(f"Warning: Could not read config file {config_file}: {e}")
            
    return defaults

def run_matlab_cmd(cmd, args):
    """Run a MATLAB command using the standalone runner."""
    workspace_root = Path(__file__).resolve().parents[2]
    utils = workspace_root / "scripts" / "stats" / "utils"
    
    runner = Path(__file__).parent / "run_matlab_standalone.py"
    
    full_cmd = [
        sys.executable, str(runner),
        cmd,
        "--utils", str(utils)
    ]
    
    if args.use_matlab:
        full_cmd.append("--use-matlab")
        if args.matlab_exe:
            full_cmd.extend(["--matlab-exe", args.matlab_exe])
        if args.spm_path:
            full_cmd.extend(["--spm-path", args.spm_path])
    else:
        if args.mcr:
            full_cmd.extend(["--mcr", args.mcr])
        if args.standalone:
            full_cmd.extend(["--standalone", args.standalone])
    
    print(f"Running: {cmd}")
    subprocess.check_call(full_cmd)

def main():
    defaults = get_config_defaults()
    
    parser = argparse.ArgumentParser(description="Run a sweep of statistical thresholds for CAT12 results.")
    parser.add_argument("results_dir", help="Path to the directory containing SPM.mat")
    
    # MATLAB Options
    parser.add_argument("--use-matlab", action="store_true", help="Use local MATLAB instead of standalone MCR")
    parser.add_argument("--matlab-exe", help="Path to MATLAB executable", default=defaults['matlab_exe'])
    parser.add_argument("--spm-path", help="Path to SPM12 installation (for local MATLAB)", default=defaults['spm_path'])
    
    # MCR Options
    parser.add_argument("--mcr", help="Path to MCR")
    parser.add_argument("--standalone", help="Path to run_spm12.sh")
    
    parser.add_argument("--force", action="store_true", help="Overwrite existing statistic maps")
    
    args = parser.parse_args()
    results_dir = os.path.abspath(args.results_dir)
    
    if not os.path.exists(os.path.join(results_dir, "SPM.mat")):
        print(f"Error: SPM.mat not found in {results_dir}")
        sys.exit(1)

    # 1. Standard FDR & FWE Maps (Voxel-wise)
    # Sweep configurations: (p_uncorr, p_fwe)
    sweeps = [
        (0.001, 0.05), # Standard
        (0.005, 0.05), # Relaxed uncorr
    ]
    
    for p_unc, p_fwe in sweeps:
        # Translate p_unc (0.001) to CAT12 filename string (p0.1)
        # 0.001 -> 0.1%, 0.005 -> 0.5%
        p_str = f"p{p_unc*100:g}"
        pattern = f"*_{p_str}_pkFWE{int(p_fwe*100)}*"
        
        existing = list(Path(results_dir).glob(pattern))
        if existing and not args.force:
            print(f"--- Skipping Double Threshold (p={p_unc}, FWE={p_fwe}): Results already exist. Use --force to re-run. ---")
            continue

        print(f"--- Running Double Threshold: p_unc < {p_unc}, p_fwe < {p_fwe} ---")
        cmd = f"cat12_threshold_maps('{results_dir}', 'p_unc', {p_unc}, 'p_fwe', {p_fwe}, 'both', true, 'log', true)"
        run_matlab_cmd(cmd, args)

    # 2. Effect Size Maps (Cohen's d)
    if list(Path(results_dir).glob("Cohen_d_*.nii")) and not args.force:
        print("--- Skipping Cohen's d Maps: Results already exist. ---")
    else:
        print("--- Generating Cohen's d Effect Size Maps ---")
        cmd = f"generate_effect_size('{results_dir}')"
        run_matlab_cmd(cmd, args)

    # 3. Standard FDR/FWE Voxel-wise
    # (These are often generated by cat12_threshold_maps or are already present)
    
    print("--- Sweep Complete ---")
    
    # 3. Generate the report
    report_script = Path(__file__).parent / "post_stats_report.py"
    report_html = os.path.join(results_dir, "post_stats_sweep_report.html")
    print(f"--- Generating HTML Report: {report_html} ---")
    
    report_cmd = [sys.executable, str(report_script), results_dir, report_html]
    if args.spm_path:
        report_cmd.extend(["--spm-path", args.spm_path])
        
    subprocess.check_call(report_cmd)

if __name__ == "__main__":
    main()
